/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as PlanTokenRouteImport } from './routes/plan.$token'
import { Route as QAccessTokenRouteImport } from './routes/q.$accessToken'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalOnboardingRouteImport } from './routes/_authenticated/portal/onboarding'
import { Route as PayMockPaymentIdRouteImport } from './routes/pay.mock.$paymentId'
import { Route as AuthenticatedAdminProjectsIndexRouteImport } from './routes/_authenticated/admin/projects/index'
import { Route as AuthenticatedAdminProjectsProjectIdRouteImport } from './routes/_authenticated/admin/projects/$projectId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlanTokenRoute = PlanTokenRouteImport.update({
  id: '/plan/$token',
  path: '/plan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QAccessTokenRoute = QAccessTokenRouteImport.update({
  id: '/q/$accessToken',
  path: '/q/$accessToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalOnboardingRoute =
  AuthenticatedPortalOnboardingRouteImport.update({
    id: '/portal/onboarding',
    path: '/portal/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PayMockPaymentIdRoute = PayMockPaymentIdRouteImport.update({
  id: '/pay/mock/$paymentId',
  path: '/pay/mock/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProjectsIndexRoute =
  AuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectsProjectIdRoute =
  AuthenticatedAdminProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/plan/$token': typeof PlanTokenRoute
  '/q/$accessToken': typeof QAccessTokenRoute
  '/portal/onboarding': typeof AuthenticatedPortalOnboardingRoute
  '/pay/mock/$paymentId': typeof PayMockPaymentIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/plan/$token': typeof PlanTokenRoute
  '/q/$accessToken': typeof QAccessTokenRoute
  '/portal/onboarding': typeof AuthenticatedPortalOnboardingRoute
  '/pay/mock/$paymentId': typeof PayMockPaymentIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/plan/$token': typeof PlanTokenRoute
  '/q/$accessToken': typeof QAccessTokenRoute
  '/_authenticated/portal/onboarding': typeof AuthenticatedPortalOnboardingRoute
  '/pay/mock/$paymentId': typeof PayMockPaymentIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/build'
    | '/admin'
    | '/plan/$token'
    | '/q/$accessToken'
    | '/portal/onboarding'
    | '/pay/mock/$paymentId'
    | '/admin/'
    | '/portal/'
    | '/admin/projects/$projectId'
    | '/api/public/payments/webhook'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/build'
    | '/plan/$token'
    | '/q/$accessToken'
    | '/portal/onboarding'
    | '/pay/mock/$paymentId'
    | '/admin'
    | '/portal'
    | '/admin/projects/$projectId'
    | '/api/public/payments/webhook'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/build'
    | '/_authenticated/admin'
    | '/plan/$token'
    | '/q/$accessToken'
    | '/_authenticated/portal/onboarding'
    | '/pay/mock/$paymentId'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/projects/$projectId'
    | '/api/public/payments/webhook'
    | '/_authenticated/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  PlanTokenRoute: typeof PlanTokenRoute
  QAccessTokenRoute: typeof QAccessTokenRoute
  PayMockPaymentIdRoute: typeof PayMockPaymentIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/plan/$token': {
      id: '/plan/$token'
      path: '/plan/$token'
      fullPath: '/plan/$token'
      preLoaderRoute: typeof PlanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$accessToken': {
      id: '/q/$accessToken'
      path: '/q/$accessToken'
      fullPath: '/q/$accessToken'
      preLoaderRoute: typeof QAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/onboarding': {
      id: '/_authenticated/portal/onboarding'
      path: '/portal/onboarding'
      fullPath: '/portal/onboarding'
      preLoaderRoute: typeof AuthenticatedPortalOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pay/mock/$paymentId': {
      id: '/pay/mock/$paymentId'
      path: '/pay/mock/$paymentId'
      fullPath: '/pay/mock/$paymentId'
      preLoaderRoute: typeof PayMockPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects/$projectId': {
      id: '/_authenticated/admin/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProjectsProjectIdRoute: typeof AuthenticatedAdminProjectsProjectIdRoute
  AuthenticatedAdminProjectsIndexRoute: typeof AuthenticatedAdminProjectsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminProjectsProjectIdRoute:
      AuthenticatedAdminProjectsProjectIdRoute,
    AuthenticatedAdminProjectsIndexRoute: AuthenticatedAdminProjectsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalOnboardingRoute: typeof AuthenticatedPortalOnboardingRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalOnboardingRoute: AuthenticatedPortalOnboardingRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  PlanTokenRoute: PlanTokenRoute,
  QAccessTokenRoute: QAccessTokenRoute,
  PayMockPaymentIdRoute: PayMockPaymentIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
